name: point_pillar_S2Rformer_kitti
save_path: ./your_path
root_dir: ./KITTI/training
root_dir_target: ./KITTI/training
validate_dir: ./KITTI/val

yaml_parser: "load_point_pillar_params"
train_params:
  DA_training: Dual_DA
  da_training: &da_training false
  batch_size: &batch_size 2
  epoches: &epoches 90
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 1

fusion:
  core_method: 'KittiIntermediateFusionDataset'
  args: []

preprocess:
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 8]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  cav_lidar_range: &cav_lidar [-70.4, -40, -3, 70.4, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

postprocess:
  core_method: 'VoxelPostprocessor'
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl'
  max_num: 100
  nms_thresh: 0.15

model:
  core_method: point_pillar_S2Rformer
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0
    backbone_fix: false
    da_training: *da_training

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
    shrink_header:
      kernal_size: [3]
      stride: [2]
      padding: [1]
      dim: [256]
      input_dim: 384

    deformable_fusion:
      input_dim: 256
      mlp_dim: 256
      agent_size: *max_cav
      window_size: 4
      dim_head: 32
      drop_out: 0.1
      depth: 3
      mask: true
      win_att: false
      grid_att: false
      cwin_att: false
      dw_att: true
      select_nn: true
      b_size: *batch_size
      max_min: true
      multi_window_size: [4, 8]

    AdvGRL: false
    advGRL_threshold: 30.0
    DA_feature_head: 256
    DA_instance_head: 88
    DA_feature_weight: 0.1
    DA_instance_weight: 0.1
    grl_feature_weight: 0.1
    grl_instance_weight: 0.1

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0
